@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_barber_account
POST {{baseUrl}}/create/barber
Content-Type: application/json

{
    "fullName": "Douglas Welber",
    "email": "douglas.welber2@outlook.com",
    "password": "123456"
}

### 

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "douglas@outlook.com",
    "password": "123456"
}